# Generated by Django 5.1.2 on 2025-11-01 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_applicant_status_alter_connection_reviewer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='Reviewer_Comments',
            field=models.CharField(blank=True, choices=[('Installation pending', 'Installation pending'), ('Documents Verification in progress', 'Documents Verification in progress'), ('Installation completed', 'Installation completed'), ('KYC failed', 'KYC failed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='Reviewer_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
    ]
